### ISSUE TITLE
404 в тегах

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#10]
Приветствую тебя, разработчик!
Обнаружил некоторую проблему с тегам.

Ели кликнуть по такому виду тега:

![image](https://user-images.githubusercontent.com/20350848/99187639-e828c480-2768-11eb-93d4-4407d85c1e60.png)
то результат такой:
![image](https://user-images.githubusercontent.com/20350848/99187700-38078b80-2769-11eb-9966-ed94df31312a.png)
если по такому:
![image](https://user-images.githubusercontent.com/20350848/99187737-5cfbfe80-2769-11eb-995a-127fde0818d0.png)
то такой результат:
![image](https://user-images.githubusercontent.com/20350848/99187752-6edda180-2769-11eb-962f-fbcd52783c5b.png)
если по такому:
![image](https://user-images.githubusercontent.com/20350848/99187768-8ddc3380-2769-11eb-8101-4c8e5b5dd5d2.png)
то такой рез - т:
![image](https://user-images.githubusercontent.com/20350848/99187790-a9dfd500-2769-11eb-94cb-7366b9907925.png)

Речь идет об этих тегах:
![image](https://user-images.githubusercontent.com/20350848/99187799-b401d380-2769-11eb-8d6e-476799a7893d.png)

**Comment by ziracms** [comment]
Спасибо, исправлю
