### ISSUE TITLE
Мерцание сайдбара админки

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#12]
Приветствую!

С чем связано периодическое мерцание красноватое сайдбара админки? Если страницу обновишь, то все норм
![image](https://user-images.githubusercontent.com/20350848/102014131-822e5d80-3d65-11eb-8080-9a9d134a1142.png)

**Comment by ziracms** [comment]
Связь с сервером теряется

**Comment by MyBlood** [comment]
> Связь с сервером теряется

Это говорит о плохом? Раньше такого никогда не было. С сервером проблемы?

**Comment by ziracms** [comment]
Либо сервер, либо сам интернет

**Comment by MyBlood** [comment]
> Либо сервер, либо сам интернет

это лишь часть проблемы, сейчас заметил, что постоянно слетает авторизация, страницу  обновляешь - снова авторизован

**Comment by ziracms** [comment]
Если авторизация слетела, то она не восстановится после обновления страницы. Придется авторизовываться заново. Полагаю, что это также связано со связью с сервером.

**Comment by MyBlood** [comment]
> Если авторизация слетела, то она не восстановится после обновления страницы. Придется авторизовываться заново. Полагаю, что это также связано со связью с сервером.

да, я понимаю. Правильнее будет сказать, что не слетает авторизация, а пропадает сайдбар админки периодами
