### ISSUE TITLE
Перенос по строкам в редакторе (при создании обычного .txt файла)

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#14]
Привет, разработчик, и с Новым Годом!

Могли бы вы сделать возможность опцию устанавливать "Перенос по строкам"? Чтобы не было при просмотре нижнего скроллбара, и весь текст можно было бы читать без прокрутки по горизонтали?
![image](https://user-images.githubusercontent.com/20350848/103560012-1fddfe00-4ec8-11eb-99ca-c80e8d9af624.png)

**Comment by ziracms** [comment]
Приветствую! С Новым Годом!
Попробую.

**Comment by MyBlood** [comment]
> Приветствую! С Новым Годом!
> Попробую.

Спасибо!

**Comment by ziracms** [comment]
Загрузил в репозиторий, можно пробовать

**Comment by MyBlood** [comment]
> Загрузил в репозиторий, можно пробовать

это по дефолту идет, или опция в редакторе появилась?

**Comment by ziracms** [comment]
Нет, опция в меню.
Добавил ещё опцию показа номера строки только что, а также подсветку закрывающего тега.
