### ISSUE TITLE
Сортировка сообщений в чате

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#15]
Приветствую тебя, разработчик!

Можно ли как - то сделать так, что бы новые сообщения в чате отображались вверху?

**Comment by ziracms** [comment]
Сделать-то можно, но зачем ?
Это надо переписать код в assets/js/chat/chat.js
В строке 84 нужно заменить **append** на **prepend**. 
Кроме того, придется переделать скроллинг окна наверх.

**Comment by MyBlood** [comment]
> Сделать-то можно, но зачем ?
> Это надо переписать код в assets/js/chat/chat.js
> В строке 84 нужно заменить **append** на **prepend**.
> Также придется поменять сортировку в самом SQL запросе, видимо. Хотя лучше просто реверснуть результаты в PHP.
> Кроме того, придется переделать скроллинг окна наверх.
> В общем, я бы не стал заморачиваться.

да уж, не думал, что это такой геммор)
