### ISSUE TITLE
Права доступа. Экстра поля

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#16]
Приветствую, разработчик!

Сделайте, пожалуйста, возможность полю задавать видимость. Т.е. опцию полю, чтобы его мог видеть только зарегистрированный пользователь, а для гостей оно не отображалось.
Спасибо.

**Comment by ziracms** [comment]
Новый функционал пока добавляться больше не будет.

**Comment by MyBlood** [comment]
> Новый функционал пока добавляться больше не будет.

Очень жаль(
