### ISSUE TITLE
Почему - то в поиске не опубликованную запись показывает

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#2]
Почему - то в поиске не опубликованную запись показывает.
При переходе по ней - 404 ошибка
![Image of Yaktocat](https://sun9-45.userapi.com/c857132/v857132561/1d0594/GaT5ywqshGU.jpg)

**Comment by ziracms** [comment]
На сайте присутствуют ссылки на эту запись ?

**Comment by MyBlood** [comment]
> На сайте присутствуют ссылки на эту запись ?

Нет, они просто есть в админке, неопубликованные.
Может это конечно с админской учетки они отображаются, если гостем зайти на сайт и засерчить, то не проверял

**Comment by ziracms** [comment]
Незнаю, как они оказались в индексе, вроде поисковики не индексируют страницы с кодом 404 вообще.
И на сайте они тоже не должны отображаться.
Может они были опубликованы когда-то, а потом вы их сняли с публикации ?

**Comment by MyBlood** [comment]
> Незнаю, как они оказались в индексе, вроде поисковики не индексируют страницы с кодом 404 вообще.
> И на сайте они тоже не должны отображаться.
> Может они были опубликованы когда-то, а потом вы их сняли с публикации ?

не в индексе поисковиков, а в результатах поиска внутри сайта

**Comment by ziracms** [comment]
Понятно, проверю

**Comment by MyBlood** [comment]
> Понятно, проверю

Ну что, не нашли баг?

**Comment by ziracms** [comment]
Еще не дошли руки. Если мне не изменяет память, что-то подобное уже было.
Надо проверить, это воспроизводится с новыми записями или только со старыми.

**Comment by MyBlood** [comment]
> Еще не дошли руки. Если мне не изменяет память, что-то подобное уже было.
> Надо проверить, это воспроизводится с новыми записями или только со старыми.

Это вопрос?

**Comment by ziracms** [comment]
У меня в последней версии не воспроизводится.
Если у вас этот баг снова появится, то откройте топик и прикрепите пошаговые действия, чтобы можно было воспроизвести баг.
