### ISSUE TITLE
Помощь в устранении ошибки

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#3]
Помогите исправить следующую ошибку (и что она значит), откуда взялась, не пойму, раньше ее точно не было
![Image of Yaktocat](https://screens.neohoster.xyz/screens-1/2020-09-16_1240.jpg)

**Comment by ziracms** [comment]
Полагаю, папка, где хранятся файлы сессии, недоступна для записи.

**Comment by MyBlood** [comment]
> Полагаю, папка, где хранятся файлы сессии, недоступна для записи.

понял, спасибо, проверю

**Comment by MyBlood** [comment]
> Полагаю, папка, где хранятся файлы сессии, недоступна для записи.

Какая именно? **/var/lib/lsphp/sessions** или **/zira/sessions.php** ?
Если на вторую, то я проверил чмд на нее, все в порядке.

**Comment by ziracms** [comment]
Читайте текст ошибки, там написано-же /var/lib/lsphp/session

**Comment by MyBlood** [comment]
> Читайте текст ошибки, там написано-же /var/lib/lsphp/session

Спасибо, попробуем!
