### ISSUE TITLE
Ошибка при открытии модуля Push - уведомлений

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#4]
Приветствую.

Что за ошибка и как ее исправить?
![Image of Yaktocat](https://screens.neohoster.xyz/screens-1/2020-09-22_1292.jpg)

**Comment by ziracms** [comment]
Переведите через гугл и думаю будет понятно, что делать.
Отключите mbstring.func_overload в настройках php

**Comment by MyBlood** [comment]
> Переведите через гугл и думаю будет понятно, что делать.
> Отключите mbstring.func_overload в настройках php

да, это достаточно простоя проблема, но из - за гребанного FastCGI ни в какую не хотел отключать эту функция, даже не взирая на то, что она прописана на 0 в php.ini

**Comment by ziracms** [comment]
Может вы не тот php.ini редактируете ?
Откройте phpinfo() и посмотрите какой файл грузится в "Loaded Configuration File"

**Comment by MyBlood** [comment]
> Может вы не тот php.ini редактируете ?
> Откройте phpinfo() и посмотрите какой файл грузится в "Loaded Configuration File"

Спасибо, проверю.
