### ISSUE TITLE
Watermark на картинки в модуле форума

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#5]
Привет, разработчик!

Подскажи, что можно подредачить, чтобы ватермарки накладывались на картинки, которые загружаются на форум?

Спасибо

**Comment by ziracms** [comment]
forum/models/file.php -> storeFiles()

**Comment by MyBlood** [comment]
> forum/models/file.php -> storeFiles()

добавить переменную форум?)
![Image of Yaktocat] (https://screens.neohoster.xyz/screens-1/2020-10-05_1437.jpg)

**Comment by ziracms** [comment]
добавить вставку водяного знака в изображение при сохранении.
про какую переменную вы спрашиваете ?
нужно доработать эту функцию

**Comment by ziracms** [comment]
добавить вставку водяного знака в изображение при сохранении.
про какую переменную вы спрашиваете ?
нужно доработать эту функцию
