### ISSUE TITLE
Вложения на форуме

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#6]
Еще раз приветствую!

Скажите пожалуйста, можно как - то сделать так, что бы хайд со вложениями был по умолчанию раскрыт, вот я о чем:

![Image of Yaktocat](https://screens.neohoster.xyz/screens-1/2020-10-05_1434.jpg)
![Image of Yaktocat](https://screens.neohoster.xyz/screens-1/2020-10-05_1435.jpg)

Спасибо!

**Comment by ziracms** [comment]
Попробуйте добавить css-класс в шаблоне.
Какой конкретно не помню, посмотрите через инспектор.
