### ISSUE TITLE
Разница в виджетах

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#7]
Приветствую!

Скажите, в чем разница в этих двух виджетах?
![Image of Yaktocat](https://screens.neohoster.xyz/screens-1/2020-10-18_1472.jpg) - **Меню пользователя**
![Image of Yaktocat](https://screens.neohoster.xyz/screens-1/2020-10-18_1471.jpg) - **Меню пользователя со всплывающим окном**

Если их смотреть, то они ничем на сайте не отличаются

**Comment by ziracms** [comment]
Всплывающее окно позволяет вводить логин и пароль не уходя со страницы

**Comment by MyBlood** [comment]
> Всплывающее окно позволяет вводить логин и пароль не уходя со страницы

т.е. мне нужно разлогиниться, чтобы увидеть это?

**Comment by MyBlood** [comment]
> Всплывающее окно позволяет вводить логин и пароль не уходя со страницы

все, разлогинился, потестил, понял. 
По сути, один и тот же виджет. Разница лишь в том, что при нажатии на кнопку "Войти" открывается всплывающее окно:
![image](https://user-images.githubusercontent.com/20350848/96495386-76845600-1250-11eb-8699-3ae0562d1976.png)
