### ISSUE TITLE
Последние темы форума

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#8]
Привет!

Скажите, будет ли виджет для вывода последних тем с форума?

**Comment by ziracms** [comment]
Вроде был последних сообщений

**Comment by MyBlood** [comment]
![Image of Yaktocat](https://screens.neohoster.xyz/screens-1/2020-10-19_1487.jpg)
![image](https://user-images.githubusercontent.com/20350848/96481173-dc1e1580-1243-11eb-8b77-8b1c57de314f.png)
![image](https://user-images.githubusercontent.com/20350848/96481235-efc97c00-1243-11eb-86aa-cb8f982c9830.png)
![image](https://user-images.githubusercontent.com/20350848/96481264-fbb53e00-1243-11eb-973b-8ef2113470b6.png)
![image](https://user-images.githubusercontent.com/20350848/96481304-096ac380-1244-11eb-9b44-4305165ae3f8.png)
что - то не вижу

**Comment by ziracms** [comment]
"Обсуждаемое на форуме" не нравится ?

**Comment by MyBlood** [comment]
> "Обсуждаемое на форуме" не нравится ?

Нравится, но просто это не совсем то=)

**Comment by ziracms** [comment]
Что с этим виджетом не так ?

**Comment by MyBlood** [comment]
> Что с этим виджетом не так ?

Все так, просто смысл разный) Где самые топовые темы, а где просто последние созданные)
