### ISSUE TITLE
Настройка прав

### ISSUE THREAD

**Issue by MyBlood** [ziracms/zira#9]
Приветствую!

Как правильно присвоить права новой группе пользователей, чтобы этот пользователь мог только полноценно создавать, удалять, редактировать свою запись? Нужно создавать отдельную категорию новостей, куда будут попадать только записи, созданные пользователями из специальной группы?

**Comment by ziracms** [comment]
Для этого потребуется написать соответствующий модуль. Система позволяет ограничить доступ к админ-панеле, но человек с правами на редактирование сможет редактировать все записи, независимо от автора.
